### ISSUE TITLE
JSON import bug

### ISSUE THREAD

**Issue by ldstevens** [verbb/feed-me#260]
yo Josh 😎 

Converting a little side project to Craft and ran across this bug(?)...

JSON:
`{
    "items": [
       {
            "title": "Entry 1"
        },
        {
            "title": "Entry 2"
        }
    ]
}`

If I don't specify "items" as the Primary Element when setting up the feed, the feed import task will fail with no errors logged.

However, if I turn on dev mode and run the debug mode, I'll get Craft Exception:
>{"title":["Title is invalid."]}

I think this refers to FM's field mapping, which is saved as:
>{"title":"items\\/title", [...]

For whatever reason, it doesn't seem to like the escaped /. Setting the Primary Element means FM saves the mapping as just:
> "{"title":"title", [...]

and that works.

Cheers! :)

**Comment by engram-design** [comment]
Firstly, the lack of logging should be fixed in #251.

The issue at hand however is due to Feed Me's complicated mapping strategy, which pretty much requires the use of a primary element if one is required. In this case, its trying to map an array:

```
array(
  [0] => Entry 1
  [1] => Entry 2
)
```

to the title, which is obviously invalid. This will all be changed for the next major version of Feed Me (a Craft 3 compatible version).

**Comment by engram-design** [comment]
This has been improved in Feed Me 3.x.
