### ISSUE TITLE
Unique Identifier check with Title will strip whitespace before checking

### ISSUE THREAD

**Issue by joepagan** [verbb/feed-me#261]
This could have been fixed since `2.0.0 beta 1` (Sorry don't have time to test this further, and, I've updated to `2.0.7` now), but, thought I would mention it. In addition, no need to rush as I am using an entry's slug now as the unique identifier.

When running Feedme on a cron, it will search for a dupe entry, Feedme strips whitespace before and after the title before checking if an entry with that title already exists. 
This can cause a new version of the same entry to be made until it reaches the `maxSlugIncrement`

**Comment by engram-design** [comment]
After a bit of investigation the short of this is it won't be fixed until the next major version of Feed Me for Craft 3. Simply because of how querying for existing elements works with exact matches. Some time ago, we used `search()`, but that has massive performance issues. I can't seem to find a way to query entries using values with whitespace in the title.

But, as I mentioned, this will all be greatly changed in Craft 3 itself, so shelving until then.

**Comment by engram-design** [comment]
This has been implemented in Feed Me 3.x.
