### ISSUE TITLE
Undefined variable: date - DateHelper.php:48

### ISSUE THREAD

**Issue by Nordicdesign** [verbb/feed-me#295]
### Description

When I create a XML feed and run the feed, even if there are errors the UI shows as completed, and you have to go to errors to find out what happened. 

In my case, an error stopped the feed from importing:
_Undefined variable: date - DateHelper.php:48_

I'm trying to import a Wordpress XML feed, and the plugin successfully recognises the date field. 

![2018-04-11 at 07 13](https://user-images.githubusercontent.com/4093514/38599326-f7ab4214-3d57-11e8-9136-135cb5329306.png)

### Steps to reproduce

1. Run craft locally with MAMP
2. Create a feed with a file saved on the local sever (e.g. http://localhost:8888/craft/web/Posts-Export-2018-April-08-1145.xml)
3. Configure the feed and run it
4. Check the logs

### Additional info

- Plugin version: 3.0.0-beta4
- Craft version: 3.0.1 solo

**Comment by engram-design** [comment]
@Nordicdesign Feed Me was identifying this as a timestamp, which it sort of is, but sort of isn't. How have you exported that `Date` value from Wordpress? Its not really a timestamp, or any sort of valid date string.

However, I have added new parsing options of `yyyymmdd` and `yyyyddmm`. Please be sure to update and select the appropriate value in the `formatting` dropdown.

Fixed in [3.0.0.beta-5](https://github.com/verbb/feed-me/releases/tag/3.0.0.beta-5).

**Comment by Nordicdesign** [comment]
I exported the posts using a plugin called WP-All-Export. By default date is exported as yyyymmdd, so I assumed that was a good format. Seems like every developer knows that's a bad idea, as I tried a different craft plugin (the old _import_) and failed too, until my wife told me to use timestamp, as the ultra logical thing to do. 

 Maybe there's a need for some documentation about the format in which certain fields are expected.
