### ISSUE TITLE
Skip running as task when only 1 item to import

### ISSUE THREAD

**Issue by green-plastic** [verbb/feed-me#318]
### Description
I'm not sure if this possible, but sometimes the import has to wait for other tasks to finish running. At times, that could be awhile (delete stale cache comes to mind).

If the import is 1 item, have a way to skip running as a task and do a direct save, is it possible?

### Additional info

- Plugin version: 2.0.11
- Craft version: 2.6.3015

**Comment by engram-design** [comment]
There's currently no way to have this work, and is actually by design. Even if there is only a single entry (element) to be imported, there are many other variables that can cause a feed processing to be less than instant (downloading assets, matrix fields, etc). For this reason, Feed Me will always run imports as Tasks, which would otherwise be triggered synchronously, as opposed to asynchronously.

Simply put - there are no plans to support this for performance reasons.

Having said that, you can run the Debug action, which circumvents the Tasks process and runs the feed processing synchronously. A word of warning - this will cause the PHP process on your server to allocate its resources to Feed Me, potentially stalling requests to the front-end or control panel. For this reason, you should only use this locally. I might suite your needs however!

**Comment by green-plastic** [comment]
Ahh bummer. Makes sense though. Thanks for the detailed response.
