### ISSUE TITLE
How to access JSON attributes using on-demand capture?

### ISSUE THREAD

**Issue by colinwilson** [verbb/feed-me#320]
### Description
partial JSON output:
```
{
  "sha": "bd7f089b1cbb4f3d8dba1da46f35ad325ffe85c2",
  "commit": {
    "author": {
      "name": "Josh Crawford",
      "email": "joshua@sgroup.com.au",
      "date": "2017-12-14T18:49:35Z"
    },
    "committer": {
      "name": "Josh Crawford",
      "email": "joshua@sgroup.com.au",
      "date": "2017-12-14T18:49:35Z"
    },
    "message": "changelog",
    "tree": {
      "sha": "8d57c715887418bbe4c1caf2719e7f00988a61c8",
      "url": "https://api.github.com/repos/verbb/feed-me/git/trees/8d57c715887418bbe4c1caf2719e7f00988a61c8"
    },
    "url": "https://api.github.com/repos/verbb/feed-me/git/commits/bd7f089b1cbb4f3d8dba1da46f35ad325ffe85c2",
    "comment_count": 0,
    "verification": {
      "verified": false,
      "reason": "unsigned",
      "signature": null,
      "payload": null
    }
  },
```
Trying to access the `name` attribute (commit->author->name) using the following?
```
{% set params = {
    url: 'https://api.github.com/repos/verbb/feed-me/commits/master',
    type: 'json',
    cache: 60,
} %}

{% set feed = craft.feedme.feed(params) %}

{% for node in feed %}
    {{ node.commit.author.name }}
{% endfor %}
```
error:

> Twig Runtime Error – Twig_Error_Runtime
> Impossible to access an attribute ("commit") on a string variable ("bd7f089b1cbb4f3d8dba1da46f35ad325ffe85c2").

results of [{{ dump(node) }}](https://pastebin.com/0gCaRCtL)

### Additional info

- Plugin version: 3.0.0-beta.13
- Craft version: 3.0.5

**Comment by engram-design** [comment]
As you've stated this is just an excerpt of your feed, I'd probably need more information. However, in this example, you're not returning an array of content, just a single JSON object (which gets converted in a single multidimensional array).

This is why you'd use `{{ feed.commit.author.name }}` rather than looping through each 'node' in the feed - there are none!

Now, it would be different if your feed was:
```
[
  {
    "commit": {
      "author": {
        "name": "Josh Crawford",
      }
  },
  {
    "commit": {
      "author": {
        "name": "Josh Crawford",
      }
  }
]
```

Because its an array, with two items in it. As such, you'd likely want to loop through it.

**Comment by colinwilson** [comment]
Ah, I see. Thank you.
