### ISSUE TITLE
Appending rows to a Super Table field

### ISSUE THREAD

**Issue by samlester** [verbb/feed-me#326]
### Description
Is there an option to add rows to a Super Table field without overwriting the existing data?

I'm creating an import that would be run each day and I'd like it to add to the rows that are present. For example this might be the feed one day:

```
{
  "id": 101,
  "date": "28/05/2018",
  "text": "Hello world"
}
```

And then this would be the next day:

```
{
  "id": 101,
  "date": "29/05/2018",
  "text": "Lorem ipsum"
}
```

At the moment the table has one row after the second run (just the latest data). Is it possible to add to the table each time the feed is processed? Am I missing something really obvious here?

### Steps to reproduce

1. Set up a feed to import into a Super Table field
2. Import the feed
3. Previous information is erased

### Additional info

- Plugin version: 2.0.11
- Craft version: 2.6.3016

**Comment by engram-design** [comment]
At the moment, there's no option for this, and its not something planned for the 2.x version. We'll be adding Super Table support (including this functionality) into the 3.x versions - as we've already done so with Matrix fields.

**Comment by samlester** [comment]
@engram-design Ok, thanks for the info!

**Comment by arunbasnet** [comment]
@samlester, cc: @engram-design   
Hey there, I stumbled across this and I am stuck at a step which you possibly have already successfully imported.  
I am looking to import a list of items using feed-me. Each item in the list would contain three items 

- date
- title
- link

My attempt is to import it as:

```
Block:
<date> - <title> - <row>
<date> - <title> - <row>
<date> - <title> - <row>
```

I keep on getting new blocks created with each row and I keep getting: 

```
Block: 
<date> - <title> - <row>
``` 
```
Block: 
<date> - <title> - <row>
``` 
```
Block: 
<date> - <title> - <row>
``` 

I cannot, for the love of me, figure out a working xml format for this. I am assuming that since it needs to loop, something like this would work, but obviously I am missing something in there.

```
<entry>
  <list>
    <listItem>
      <date></date>
      <title></title>
      <link></link>
    </listItem>
    <listItem>
      <date></date>
      <title></title>
      <link></link>
    </listItem>
  </list>
</entry>
```

**Comment by samlester** [comment]
@arunbasnet We were never able to get this working as the functionality wasn't available in the 2.x version of Feed Me. We ended up using related entries for each row instead.

**Comment by tibbis** [comment]
How did you guys solve this exactly, for **appending** data to lists such as a matrix field? Can figure out any way to do it.
