### ISSUE TITLE
Multiple tags/categories in a csv

### ISSUE THREAD

**Issue by echantigny** [verbb/feed-me#334]
### Description
I am importing a CSV with a tag field, which contains a comma delimited list of terms.  I would like to be able to import them as separate tags, but it's taking the whole string as one right now.

Tested the same thing with categories and it still holds true.

It would be great if we could type in a delimiter and they imported in a separate tag or category.

### Additional info

- Plugin version:

Craft Commerce | 2.0.0-beta.5
Feed Me : 3.0.0-beta.15
Feed Me Pro: 3.0.4

- Craft version: Craft Solo 3.0.11

**Comment by engram-design** [comment]
The problem is, a column in your CSV that's also comma delimited just isn't going to work for Feed Me, it'll just confuse it where the next column's value should start. To get around this, we've included (undocumented for the moment) the pipe character `|` for this functionality.

`Category 1|Category 2` for instance.

**Comment by engram-design** [comment]
We'll certainly consider this. I think the win-win solution for everyone will be to have this delimiter as a config option as you've mentioned. We'll have this in the next release.

**Comment by eric-chantigny** [comment]
That sounds great.  I will definitely test this feature as soon as it's in.  Thank you

**Comment by gudehus** [comment]
I've got a similar problem, but with a XML file. Neither multiple <category> tags nor the solution with the pipe character will bring me multiple categories for a product.

**Comment by gudehus** [comment]
And here is the solution I've found in another thread. 
<Categories>
    <Category>First Category</Category>
    <Category>Second Category</Category>
</Categories>

Documentation could be better. But awesome tool.

**Comment by echantigny** [comment]
@engram-design I managed to replace the commas for my categories and tags with a pipe "|" and it did work.  It would be better if we could modify it in the parameters of the feed, but it does the trick for me for now.

**Comment by engram-design** [comment]
Added a config option in [3.0.0-beta.16](https://github.com/verbb/feed-me/releases/tag/3.0.0-beta.16). Please use `dataDelimeter` to set the character you wish to delimit multiple chunks of data with (for any type of datatype - not just CSV)

**Comment by billythekid** [comment]
Sorry to comment on a closed issue, can this be extended to asset fields too? tried piping multiple URLs but it just took the first it appears. (I guess because URLs can have pipes in them) (using 3.0.0-beta.17)

Is there a format that should be used for URLs to identify multiple URLs for assets fields?

**Comment by billythekid** [comment]
Sorry Josh, ignore me, I was being an idiot, I'd only copied the same URL as the one after the pipe! Time to head home for the day I think!
