### ISSUE TITLE
Question: Import task seems to update all records each run with add & update import strategy 

### ISSUE THREAD

**Issue by jamesmacwhite** [verbb/feed-me#356]
### Description

I just wanted to clarify the behaviour of the import task if possible. I'm using the add & update import strategy and using a fixed unique ID field present on each XML item node as the field to test whether a record exists already. The import process itself creates/updates entries within a set section. The import task is working fine, but I've notice that each time its run the step count for the task is always the same amount of items from the feed URL. Is this to be expected? It seems each time the feed import is run is taking the same amount of time to import. With the update strategy and having `checkExistingFieldData` set to `true` in my FeedMe config, I thought after the initial import, subsequent runs would be quicker? I tested by doing a full import and then running it again immediately after. It is taking the same time, which indicates it is updating each record over and over again, rather than skipping.

I've tried selecting the title as the unique field for checking, but the same occurs. I'm not sure however if this is by design or not.

Just looking for clarification on the expected output from the task based on the configuration above.

### Additional info

- Plugin version: 2.0.12
- Craft version: 2.6.3019

**Comment by engram-design** [comment]
That's reasonable expected behaviour. `checkExistingFieldData` is a bit of a stop-gap for _some_ fields to help with updating content for fields more the necessary. Particular, for fields that are slow to do this (element fields), typically the more fields you have to update the slower the processing. However, the same can't be said for element attributes, which are updated regardless. As such, this config setting works well when you're mapping to a lot of custom fields.

If you have the feed setup to Add & Update, you'll never have the case where it skips elements altogether. At the very least, you'll be updating an element's Title, Slug, etc (depending on what you're mapping) and maybe none of your custom fields have changed. It will also fire the `saveElement()` function, even if nothing has changed. Unfortunately, this is the slowest part of the feed process, and something that isn't improved until Craft 3.

To further clarify, this is all for Craft 2.

**Comment by jamesmacwhite** [comment]
@engram-design Thanks for clarifying Josh, that's fine then it all seems normal behaviour based on the above. Looking at the logs the average time for the task is 244 seconds, which is 4 minutes for 700 XML items, which isn't too bad.
