### ISSUE TITLE
Importing products with same slug (or SKUs) as existing products can cause errors

### ISSUE THREAD

**Issue by oadslug** [verbb/feed-me#374]
### Description

Not sure if this a feature or a bug, but something to be aware of. When importing products, it's possible to import a product with the same slug and/or variant SKUs as existing products, causing integrity errors.

### Steps to reproduce

1. Have an existing product. 
2. Run an import, importing same product (same slug), but matched on a field that isn't defined on the existing product (i.e. 'previousId' for example).
3. The product will get imported and there will now be 2 matching products (same title and slug).
4. Viewing/clicking on the previous product will produce Yii error ('Creating default object from empty value').

### Additional info

Plugin version: FeedMe 3.0.0-beta.17, FeedMe Pro 3.0.4, Commerce 2.0.0-beta.7
Craft version: Craft CMS 3.0.19

**Comment by oadslug** [comment]
fyi... this can also happen if you import the same products into different product types. (I only did this so that I could later re-type the products manually after import). There are also some knock-on effects, even if you later delete the offending duplicates. For example, the imported products `defaultVariantId` will be set to the newest import, and the old product `defaultVariantId` will be set to `null` — creating integrity errors/system crash. Might be best to fail the import if there are any matching slugs/skus in the system.

**Comment by engram-design** [comment]
Valid point about the different product types - that's been fixed in the latest craft-3 branch.

Your first point is where it gets tricky. Technically, you are trying to import a product, if you try and import the same product, that's fine, you have have two products with the same content (even slug's will be auto-created so they don't clash). Its the attached variants (default or otherwise) that often cause the issues.

However, you've caught an interesting case here, which we should address. If you're trying to compare on a field that doesn't have a value, or if the value doesn't exist on one product, it'll match the first one. It'll then try and add the variants to that single product, which it will freak out a bit. In this instance, you'll end up with orphaned variants, throwing errors like the above `Creating default object from empty value` or integrity constraints.

I've reworked how variants act now, and they should always either modify the directly attached variants, or add new ones. You'll still always get an error message if you try and add a variant with an SKU that exists on another product - that at least is normal.
