### ISSUE TITLE
When Importing only 1 product, Primary Element drop-down displays '(x24 Elements)'

### ISSUE THREAD

**Issue by oadslug** [verbb/feed-me#378]
### Description

Minor issue, but maybe something to address at some point. When importing only 1 product the 'Primary Element' dropdown (on page 2 of setup) displays '(x24 Elements)' for some reason, but correctly imports only 1. In all other cases it seems to display the correct number of items.

### Additional info

- Plugin version: FeedMe 3.0.0-beta.18
- Craft version: Craft CMS 3.0.20

**Comment by engram-design** [comment]
This comes down to (mostly) XML based setups, and how Feed Me is unable to determine if the one item you're importing should be an array or not. Its actually counting the individual child elements. I don't believe this is an issue for JSON feeds due to the direct nature of specifying array content.

However, this should be fixed in the latest craft-3 branch for this sort of scenario.
