### ISSUE TITLE
Redactor error during import

### ISSUE THREAD

**Issue by tadward** [verbb/feed-me#400]
### Description
When running an import from an xml file a few entries do not get imported. Viewing the logs I see this error:

`Blog: Argument 1 passed to craft\redactor\FieldData::__construct() must be of the type string, array given, called in /craft/vendor/craftcms/redactor/src/Field.php on line 228 - FieldData.php:41`

I do have a Redactor field within a Matrix field.
The content for the entry has nothing out the ordinary. It has `<p>`, a single `<a>`, a few `<strong>` and a few `<br />` tags. 
The content is being pulled from a wygwam field from within ExpressionEngine.

On this particular Craft install it was only a single entry that threw this error and didn't import.
I have received this error on 2 separate craft installs for currently in development websites.

### Steps to reproduce

1. Run import of basic feed set up
2. View logs

### Additional info

- Plugin version: 3.0..0-beta.21 and 3.0.4 (Pro)
- Craft version: 3.0.25

**Comment by engram-design** [comment]
Firstly, make sure you're encoding your HTML within `CDATA` tags, otherwise Feed Me will try and parse that as part of the XML document. That _may_ be the issue.

```
<Content><![CDATA[<h3><strong>Some random text</strong></h3>]]></Content>
```

There were also some improvements with Matrix handling in [3.0.0-beta.23](https://github.com/verbb/feed-me/releases/tag/3.0.0-beta.23).
