### ISSUE TITLE
Problem with assets and duplicate entries on multi-site setup

### ISSUE THREAD

**Issue by Djive** [verbb/feed-me#429]
We have a multi-site setup of 130 sites.
Importing from XML files.
We need to import 10000+ entries into one site.
Tried with 5000 for testing purposes.
Import starts blazing fast and everything is fine for first 2500 entries, then it greatly slows down. So much even that I had to call it a day and come tomorrow to check on it. 

Tomorrow I see in logs that import was run 3 times and its still running.
- on first import it came to node #2568 then started over
- on second run it came to node #2943 then again started over
- on third run it came to node #4172 then again started over 
during this third run in the morning, i stopped it.

in between each old and new import there are 2 messages
- "Preparing for feed processing."
- "Finished preparing for feed processing"

Checking the logs I found that on first run, import was just adding entries so i am guessing thats why it was so fast, while all other imports later were checking against existing elements and thats probably the reason why they were so slow.
Although last run started at 8:11 in the morning and checked duplicates for 4181 nodes till 8:24 after which it started importing new content, so again, that seems like fast duplicate checking.
Also saw that next node in import ran into an Asset error with message "failed to open stream: No such file or directory" while i can normally access that image using the provided url.

Checking the entries shows many duplicates, even though the custom field for checking duplicates is an unique entry_id number. When I compare the two entries, they are exactly the same, craft just added "-1" to the slug of the second imported entry.
Also, assets are imported into all 130 sites which really bloats our database. Some entries have multiple assets and for each asset there are 130 rows created in craft_content table.
craft_content had over 600 000 rows after I stopped the import (it had 157 000 before import).
craft_searchindex table had over 3 milion rows after I stopped the import (it had 523 000 before import).

feed-me log is 125MB at the moment.

All settings for the site and server and set way above standard parameters.

Can you suggest anything that we can do to try and fix this?
Thanks!

- Feed Me 3.0.0-beta.30
- Craft Pro 3.0.31

**Comment by engram-design** [comment]
So firstly, what data and content are you using as the unique identifier? You mention `an unique entry_id number` but what does that refer to? I imagine its a plain text field or similar with something unique. Just make sure that you're also importing whatever field you've ticked in the unique identifier field, otherwise Feed Me won't know about it.

You mentioned multi sites - how are you importing them? Do you have a feed setup for each site? By default field elements, if set to create, will propagate across sites, but you've certainly uncovered a bug in the implementation of this, in that even if you set importing into a specific locale, it won't work. For instance, importing entries into Site A will create entries in just that site, but if you've got category/asset/etc fields in that entry, and setting to create if they don't exist, they'll be created for all sites - not good in your case!

This should be fixed in [3.0.0](https://github.com/verbb/feed-me/releases/tag/3.0.0).

**Comment by Djive** [comment]
Brandon assisted with a solution so we could import everything only to 1 site, in this ticket: https://github.com/craftcms/cms/issues/3483

We are using EE entry ID as the unique indentifier, and importing it with every import.

We split all our XMLs into smaller chunks, 1500-2000 elements and implemented Brandons fix and managed to import everything successfully.

Looking forward to 3.0.0.

Thank you

**Comment by engram-design** [comment]
@Djive Sure thing, my testing certainly showed that assets were being incorrectly propagated to each site on import, and as you say, blowing out the content table. The 3.0.0 version should fix this, but glad you could get a solution together.
