### ISSUE TITLE
Paginate logs output

### ISSUE THREAD

**Issue by exophunk** [verbb/feed-me#454]
It would be nice if you could paginate the "logs" tab in a next release, because with 50'000 log entries or something like that, the page freezes and is not able to load the content.

**Comment by engram-design** [comment]
Currently it'll only show the last 300 entries in your log, however, it still needs to read the entire file which I imagine is where its struggling with.

**Comment by engram-design** [comment]
Pagination isn't strictly possible without log items being an element (or writing our own pagination logic), but there's a better solution here I think. We've implemented log file 'rolling' so that you won't end up with one giant log file. This follows what Craft's log files do, when they reach a certain size, automatically rename to `feedme.log.1` for instance.

Added in [3.1.6](https://github.com/verbb/feed-me/releases/tag/3.1.6)
